version: "3.7"

services:
#  api:
#    build:
#      context: .
#      dockerfile: Dockerfile.api
#      target: prod
#    ports:
#      - "8000:8000"
#      - "8080:8080"
#    env_file:
#      - .env.local

  worker:
    build:
      context: .
      dockerfile: worker/Dockerfile
      target: prod
    ports:
      - "8000:8000"
      - "8080:8080"
#    env_file:
#      - .env.local

  # DB

  # etl

  # Kafka

